"""Add plan change and cancellation history tables

Revision ID: 97971bf0ef32
Revises: c1386f82f4c9
Create Date: 2025-12-21 09:41:03.134597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97971bf0ef32'
down_revision = 'c1386f82f4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_histories',
    sa.Column('cancellation_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('cancellation_type', sa.String(length=20), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_comment', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=50), nullable=True),
    sa.Column('is_forced', sa.Boolean(), nullable=True),
    sa.Column('plan_at_cancellation', sa.String(length=20), nullable=True),
    sa.Column('requested_date', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.String(length=50), nullable=True),
    sa.Column('data_retention_until', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cancellation_id')
    )
    op.create_table('plan_change_histories',
    sa.Column('history_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('old_plan', sa.String(length=20), nullable=True),
    sa.Column('new_plan', sa.String(length=20), nullable=True),
    sa.Column('old_billing_type', sa.String(length=20), nullable=True),
    sa.Column('new_billing_type', sa.String(length=20), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('prorated_amount', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_change_histories')
    op.drop_table('cancellation_histories')
    # ### end Alembic commands ###
