"""Initial migration

Revision ID: c1386f82f4c9
Revises: 
Create Date: 2025-12-21 09:16:19.539408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1386f82f4c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('billing_type', sa.String(length=20), nullable=True),
    sa.Column('balance_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cancellation_date', sa.String(length=50), nullable=True),
    sa.Column('plan_change_count', sa.Integer(), nullable=True),
    sa.Column('last_plan_change_date', sa.String(length=50), nullable=True),
    sa.Column('data_retention_until', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('billings',
    sa.Column('billing_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('billing_period', sa.String(length=7), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('base_fee', sa.Float(), nullable=True),
    sa.Column('usage_fee', sa.Float(), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('billing_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name_enc', sa.Text(), nullable=True),
    sa.Column('address_enc', sa.Text(), nullable=True),
    sa.Column('phone_enc', sa.Text(), nullable=True),
    sa.Column('email_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('operation_logs',
    sa.Column('log_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('analysis_results',
    sa.Column('result_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('analysis_date', sa.String(length=50), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('attribute_json_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    op.drop_table('operation_logs')
    op.drop_table('customers')
    op.drop_table('billings')
    op.drop_table('users')
    # ### end Alembic commands ###
